version: '3'

services:
  postgres-auth:
    image: postgres:latest
    container_name: postgres-auth
    environment:
      POSTGRES_DB: AuthDB
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 123456
    ports:
      - "5432:5432"
    volumes:
      - postgres_auth_volume:/var/lib/postgresql/data
  
  auth-api:
    container_name: auth-api

    build:
      context: ./AuthApi/
    ports:
      - "3000:3000"
 
    depends_on: 
      - postgres-auth
  
  auth-vue:
    container_name: auth-vue

    build:
      context: ./AuthVue/
    ports:
      - "8080:8080"
 
    depends_on: 
      - auth-api

volumes:
  postgres_auth_volume:
